### ISSUE TITLE
Editorial consideration for Prelude 20

### ISSUE THREAD

**Issue by phmccarty** [ksnortum/chopin-opus-28#2]
I recently learned that in most editions of Op. 28 No. 20, editors have omitted the E-flat accidental in the last chord of measure 3 (right hand), but many suspect that the omission was an oversight.

There's some background info on Wikipedia: https://en.wikipedia.org/wiki/Prelude,_Op._28,_No._20_(Chopin)#Bar_3_ambiguity

I didn't propose this as a "correction" due to the ambiguity, but it's worth considering whether to change that note to E-flat for your edition.

**Comment by ksnortum** [comment]
I've always played it with an E-natural.  I went back and played it with an e-flat and although it's possible, I think the musical line is moving to natural at that point in the piece.  So, even though I was very surprised to learn that many pianists play the e-flat, I'm going to let the e-natural stand.  

Thanks for bringing this up.

**Comment by phmccarty** [comment]
Thank you for considering it!

I learned the piece from an edition with the E-flat, so the E-natural sounds new and interesting... It certainly changes the character of measures 3-4 with the E-natural instead of E-flat :-)
